### ISSUE TITLE
Cannot run on clean install

### ISSUE THREAD

**Issue by mgamini** [electrode-io/electrode-boilerplate-universal-react-node#43]
No errors during clone or npm install. Originally tried on node 4.2.3, then 7.1.0. 

Did I do something wrong?

➜  electrode-boilerplate-universal-react-node git:(master) NODE_ENV=development gulp hot
[11:59:57] Using gulpfile ~/Dev/playground/electrode-boilerplate-universal-react-node/gulpfile.js
[11:59:57] Starting 'hot'...
[11:59:57] Starting '.webpack-dev'...
[11:59:57] Finished '.webpack-dev' after 99 μs
[11:59:57] Starting 'server-hot'...
[11:59:57] Starting 'server-watch-$deps$'...
[11:59:57] Starting '.init-bundle.valid.log'...
[11:59:57] Finished '.init-bundle.valid.log' after 6.22 ms
[11:59:57] Finished 'server-watch-$deps$' after 7.71 ms
[11:59:57] Starting 'server-watch'...
[11:59:57] Starting 'generate-service-worker'...
[11:59:57] Finished 'generate-service-worker' after 298 μs
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/garrett/Dev/playground/electrode-boilerplate-universal-react-node/server/**/* /Users/garrett/Dev/playground/electrode-boilerplate-universal-react-node/config/**/*
Entry point configuration is not found, using default entry point...
isomorphic-loader webpack plugin: removed existing config file
 70% 1/1 build modules http://localhost:2992/
webpack result is served from http://localhost:2992/js/
content is served from /Users/garrett/Dev/playground/electrode-boilerplate-universal-react-node
webpack bundle is now VALID
webpack report is served from http://localhost:2992/reporter
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`
module.js:474
    throw err;
    ^

Error: Cannot find module 'react/lib/ReactCompositeComponent'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/garrett/Dev/playground/electrode-boilerplate-universal-react-node/node_modules/electrode-react-ssr-caching/lib/ssr-caching.js:5:33)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ananavati** [comment]
@mgamini thanks for reporting the issue, looks like a module update might be causing this issue, looking into it.

**Comment by ananavati** [comment]
`+ electrode-react-ssr-caching@0.1.5` with https://github.com/electrode-io/electrode-react-ssr-caching/pull/16 should fix this issue.
