### ISSUE TITLE
Disabling local scope by default for css

### ISSUE THREAD

**Issue by tsvetant** [electrode-io/electrode-boilerplate-universal-react-node#46]
How can I do that ? 
The only information I see about the default local scope is how great it is, but nowhere how to turn that off, I don't need it. 
I noticed several modules related to that, but as newcomer it just looks like a disastrously mishandled undertaking [*](https://en.oxforddictionaries.com/definition/us/clusterfuck) 

---

Also on a new note (not opening different issue since it's minor) the webpack reporter doesn't seems to be working with fresh clone of this repo (my dev environment is a ubuntu 16.x based distro with lts node) 

    TypeError: Cannot read property '1' of null
        at ModuleProcessor._splitPathName (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/module-processor.js:55:18)
        at Object.keys.forEach (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/module-processor.js:83:26)
        at Array.forEach (native)
        at ModuleProcessor.makeModulesByPackage (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/module-processor.js:82:37)
        at Object.getModulesByPkg (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/stats-utils.js:33:29)
        at Object.json (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/webpack-reporter.js:78:34)
        at ServerResponse.res.format (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/response.js:628:13)
        at WebpackReporter._webReport (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/webpack-reporter.js:71:9)
        at Layer.handle [as handle_request] (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/layer.js:95:5)
        at next (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/route.js:131:13)
        at Route.dispatch (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/layer.js:95:5)
        at /home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/index.js:277:22
        at Function.process_params (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/index.js:330:12)
        at next (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/index.js:271:10)
        at expressInit (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/middleware/init.js:33:5)
    TypeError: Cannot read property '1' of null
        at ModuleProcessor._splitPathName (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/module-processor.js:55:18)
        at Object.keys.forEach (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/module-processor.js:83:26)
        at Array.forEach (native)
        at ModuleProcessor.makeModulesByPackage (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/module-processor.js:82:37)
        at Object.getModulesByPkg (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/stats-utils.js:33:29)
        at Object.json (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/webpack-reporter.js:78:34)
        at ServerResponse.res.format (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/response.js:628:13)
        at WebpackReporter._webReport (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/webpack-reporter.js:71:9)
        at Layer.handle [as handle_request] (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/layer.js:95:5)
        at next (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/route.js:131:13)
        at Route.dispatch (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/layer.js:95:5)
        at /home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/index.js:277:22
        at Function.process_params (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/index.js:330:12)
        at next (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/index.js:271:10)
        at expressInit (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/middleware/init.js:33:5)
    TypeError: Cannot read property '1' of null
        at ModuleProcessor._splitPathName (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/module-processor.js:55:18)
        at Object.keys.forEach (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/module-processor.js:83:26)
        at Array.forEach (native)
        at ModuleProcessor.makeModulesByPackage (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/module-processor.js:82:37)
        at Object.getModulesByPkg (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/stats-utils.js:33:29)
        at Object.json (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/webpack-reporter.js:78:34)
        at ServerResponse.res.format (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/response.js:628:13)
        at WebpackReporter._webReport (/home/tsvetant/w.storm/simple-boilerplate/node_modules/electrode-webpack-reporter/lib/webpack-reporter.js:71:9)
        at Layer.handle [as handle_request] (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/layer.js:95:5)
        at next (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/route.js:131:13)
        at Route.dispatch (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/layer.js:95:5)
        at /home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/index.js:277:22
        at Function.process_params (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/index.js:330:12)
        at next (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/router/index.js:271:10)
        at expressInit (/home/tsvetant/w.storm/simple-boilerplate/node_modules/express/lib/middleware/init.js:33:5)

**edit** To rephrase my question: How do I set in the config the 'options.mode' for postcss.plugin ? So far I did the ugly thing of editing the `postcss-modules-local-by-default` module defining `options.mode = 'global';`, but this ain't real solution.

**Comment by Jehu** [comment]
why closed?

**Comment by darkbls** [comment]
this is still a relevant question for some of us
